// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12iAiEME70-zh9vTi_dxKD4EG3QAbiHQ',
    appId: '1:974072583230:web:926054a6122f201de1ed6f',
    messagingSenderId: '974072583230',
    projectId: 'e-recruitment-59a9b',
    authDomain: 'e-recruitment-59a9b.firebaseapp.com',
    storageBucket: 'e-recruitment-59a9b.appspot.com',
    measurementId: 'G-MCDLF6HDR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0l-gVnjGXT7bACX1EzFk6yfec5RXuY-Y',
    appId: '1:974072583230:android:6b6e9571d1721fe3e1ed6f',
    messagingSenderId: '974072583230',
    projectId: 'e-recruitment-59a9b',
    storageBucket: 'e-recruitment-59a9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrsXvOD9I6FrYvIwm7sjq7R2mTS98Rkc',
    appId: '1:974072583230:ios:c2456a5afa1d3ccde1ed6f',
    messagingSenderId: '974072583230',
    projectId: 'e-recruitment-59a9b',
    storageBucket: 'e-recruitment-59a9b.appspot.com',
    iosBundleId: 'com.erecruitment.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgrsXvOD9I6FrYvIwm7sjq7R2mTS98Rkc',
    appId: '1:974072583230:ios:8260d5e3042682f5e1ed6f',
    messagingSenderId: '974072583230',
    projectId: 'e-recruitment-59a9b',
    storageBucket: 'e-recruitment-59a9b.appspot.com',
    iosBundleId: 'com.erecruitment.app.RunnerTests',
  );
}
