// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Il_4Xdkdcg-f-l8MGrdqloVJrUKseU8',
    appId: '1:1038987442498:web:ed0c67430351e3b09970db',
    messagingSenderId: '1038987442498',
    projectId: 'recruitment-f1e2a',
    authDomain: 'recruitment-f1e2a.firebaseapp.com',
    storageBucket: 'recruitment-f1e2a.appspot.com',
    measurementId: 'G-X73Q96DRCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vNwPZ2BZiZkZSx-XFXwnSwlrOt6LsIc',
    appId: '1:1038987442498:android:6e4dfd112d4479ff9970db',
    messagingSenderId: '1038987442498',
    projectId: 'recruitment-f1e2a',
    storageBucket: 'recruitment-f1e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Ftf5U1_60dbOGZIqHjBgzCvz-EwLYUU',
    appId: '1:1038987442498:ios:f3ecb52914799f7d9970db',
    messagingSenderId: '1038987442498',
    projectId: 'recruitment-f1e2a',
    storageBucket: 'recruitment-f1e2a.appspot.com',
    iosClientId:
        '1038987442498-2o85h6u361tahp4ed1qvki90flm5g02b.apps.googleusercontent.com',
    iosBundleId: 'com.recruitment.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Ftf5U1_60dbOGZIqHjBgzCvz-EwLYUU',
    appId: '1:1038987442498:ios:f3ecb52914799f7d9970db',
    messagingSenderId: '1038987442498',
    projectId: 'recruitment-f1e2a',
    storageBucket: 'recruitment-f1e2a.appspot.com',
    iosClientId:
        '1038987442498-2o85h6u361tahp4ed1qvki90flm5g02b.apps.googleusercontent.com',
    iosBundleId: 'com.recruitment.app',
  );
}
